### ISSUE TITLE
cuda fails after setting up environment

### ISSUE THREAD

**Issue by jasonlevine** [lunarring/latentblending#5]
Hello, I've been trying to set an environment to run latentblending for the last week without success.

I'm on a Debian 10 machine with an Nvidia T4 with cudatoolkit 11.6 installed

I'm using conda to setup up the env, python, pip and using pip to install the requirements like this:
```
conda create -n latentblending python==3.10 pip
conda activate latentblending
pip install -r requirements.txt
```

If I try to run example1, I get an error on _cuda_init():
```
$ python -m example1_standard.py 
No module 'xformers'. Proceeding without it.
/opt/conda/envs/latentblending/lib/python3.10/site-packages/pytorch_lightning/utilities/distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v1.10.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
autosetup_branching: num_inference_steps: 30 list_nmb_branches: [2, 3, 6, 12] list_injection_idx: [0, 20, 23, 27]
Traceback (most recent call last):
  File "/opt/conda/envs/latentblending/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/conda/envs/latentblending/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/jupyter/latentblending/example1_standard.py", line 55, in <module>
    lb.set_prompt1(prompt1)
  File "/home/jupyter/latentblending/latent_blending.py", line 161, in set_prompt1
    self.text_embedding1 = self.get_text_embeddings(self.prompt1)
  File "/opt/conda/envs/latentblending/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/jupyter/latentblending/latent_blending.py", line 794, in get_text_embeddings
    return self.sdh.get_text_embedding(prompt)
  File "/home/jupyter/latentblending/stable_diffusion_holder.py", line 255, in get_text_embedding
    c = self.model.get_learned_conditioning(prompt)
  File "/home/jupyter/latentblending/ldm/models/diffusion/ddpm.py", line 665, in get_learned_conditioning
    c = self.cond_stage_model.encode(c)
  File "/home/jupyter/latentblending/ldm/modules/encoders/modules.py", line 193, in encode
    return self(text)
  File "/opt/conda/envs/latentblending/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jupyter/latentblending/ldm/modules/encoders/modules.py", line 170, in forward
    z = self.encode_with_transformer(tokens.to(self.device))
  File "/opt/conda/envs/latentblending/lib/python3.10/site-packages/torch/cuda/__init__.py", line 229, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unexpected error from hipGetDeviceCount(). Did you run some cuda functions before calling NumHipDevices() that might have already set an error? Error 101: hipErrorInvalidDevice
```

If I then install xformers like this: `conda install xformers -c xformers/label/dev`
Running example1 segfaults immediately:
```
$ python -m example1_standard.py 
Segmentation fault
```

Any ideas how I might resolve this? Am I using the correct version of python? Has anyone succeed in running latentblending on a similar setup?

Much thanks,
Jason

**Comment by lunarring** [comment]
Hi, 
have not tried yet with T4 -- 
do you get it running without xformers?
For xformers, you could try to go for 
```pip install -q https://github.com/camenduru/stable-diffusion-webui-colab/releases/download/0.0.15/xformers-0.0.15.dev0+1515f77.d20221130-cp38-cp38-linux_x86_64.whl```

or

```pip install xformers```
